### ISSUE TITLE
Use with spatie/multinenancy

### ISSUE THREAD

**Issue by dseeger** [spatie/laravel-schedule-monitor#26]
I'm trying to use this packages on my application with multitenancy. 
I can monitor schedules per tenant with `php artisan tenants:artisan schedule-monitor:sync`
But of course if I then run `php artisan schedule:run` I get a error that no tenant DB was selected.

Is anybody running these two packages together? If so, how to go about it?

**Comment by freekmurze** [comment]
Isn't your schedule always non-tenant specific. Sure, the tasks themselves can inside them loop over each tenant, but for the scheduler it still counts as one task.

How does your schedule look like?

**Comment by dseeger** [comment]
```
protected function schedule(Schedule $schedule)
    {
        $schedule
            ->command('tenants:artisan \'backup:run --only-db\'')
            ->timezone('Europe/Berlin')
            ->daily()
            ->at('00:30');

        $schedule
            ->command('backup:monitor')
            ->timezone('Europe/Berlin')
            ->daily()
            ->at('01:00');

        $schedule
            ->command('psi:dbmaintenance')
            ->timezone('Europe/Berlin')
            ->daily()
            ->at('01:30');

        $schedule
            ->command('psi:dailyincidentemail')
            ->timezone('Europe/Berlin')
            ->dailyAt('08:30');

        $schedule
            ->command('psi:weeklyincidentemail')
            ->timezone('Europe/Berlin')
            ->weeklyOn(1, '09:00');

        $schedule
            ->command('psi:monthlyincidentemail')
            ->timezone('Europe/Berlin')
            ->monthlyOn(1, '09:30');
    }
```

The last for commands I made TenantAware. 
The schedules run fine. But when I try to run `php artisan schedule-monitor:sync` command, I get the 'No Databse selected' error. I guess the schedule-monitor tables have to be in the landlord database? But how does schedule-monitor know to use the landlord database and not look for a tenant database?

**Comment by freekmurze** [comment]
This is probably caused by `tenants:artisan` not switching back to the landlord db. This needs to be handled in spatie/multitenancy.

**Comment by masterix21** [comment]
> This is probably caused by `tenants:artisan` not switching back to the landlord DB. This needs to be handled in spatie/multitenancy.

I think that isn't the problem because all commands with `CommandTenantAware` Trait use the command execution in isolated mode with `$tenant->execute(...)`: so, it automatically restores the previous state calling `forgetCurrent()`.

@dseeger, I have simulated your code, but for me, it works. Could you create a repository on GitHub to help me to understand better, please? 

Thanks

**Comment by dseeger** [comment]
@masterix21 Sorry, I didn't notice your answer until now.
Toi be clear, the problem arises when i first run `php artisan schedule-monitor:sync` (first having created the schedule-monitor tables in the landlord database) and then `run php artisan schedule:run`. That is wehn I get the error that no tenant DB was selected.

**Comment by masterix21** [comment]
Okay, but there are no logic-connections because every time that you execute `artisan`, the tenant configuration should be reset. What's your default connection in the .env?

**Comment by dseeger** [comment]
```
DB_CONNECTION=tenant
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USERNAME=root
DB_PASSWORD=xxx
DB_LANDLORD_DATABASE=landlord
```

config/database.php
```
'default' => env('DB_CONNECTION', 'tenant'),

'connections' => [

        'landlord' => [
            'driver'         => 'mysql',
            'url'            => env('DATABASE_URL'),
            'host'           => env('DB_HOST', '127.0.0.1'),
            'port'           => env('DB_PORT', '3306'),
            'database'       => env('DB_LANDLORD_DATABASE', 'landlord'),
            'username'       => env('DB_USERNAME', 'test'),
            'password'       => env('DB_PASSWORD', ''),
            'unix_socket'    => env('DB_SOCKET', ''),
            'charset'        => 'utf8mb4',
            'collation'      => 'utf8mb4_unicode_ci',
            'prefix'         => '',
            'prefix_indexes' => true,
            'strict'         => false,
            'engine'         => null,
            'options'        => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'tenant' => [
            'driver'         => 'mysql',
            'url'            => env('DATABASE_URL'),
            'host'           => env('DB_HOST', '127.0.0.1'),
            'port'           => env('DB_PORT', '3306'),
            'database'       => env('DB_DATABASE', null),
            'username'       => env('DB_USERNAME', 'test'),
            'password'       => env('DB_PASSWORD', ''),
            'unix_socket'    => env('DB_SOCKET', ''),
            'charset'        => 'utf8mb4',
            'collation'      => 'utf8mb4_unicode_ci',
            'prefix'         => '',
            'prefix_indexes' => true,
            'strict'         => false,
            'engine'         => null,
            'options'        => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
]
```

**Comment by masterix21** [comment]
Ok. The error could be the default connection. The tenant connection is switched by laravel-multitenancy, but the landlord connection not.

Try to change it:
`DB_CONNECTION=landlord`

**Comment by dseeger** [comment]
Sorry if this is getting out of hand with my beginners questions... but:
if I do that, then all my direct DB Queries try to access the landlord Database.
`DB::table('test_table')->where('id', 1)->get();`

**Comment by masterix21** [comment]
Yes, but you can specify the connection name.
```php
DB::connection('tenant')->table('test_table')->where('id', 1)->get();
```

Or, if you use Eloquent, you can use the model trait `UsesTenantConnection`.

**Comment by dseeger** [comment]
OK, no more noob questions. All is working now!
Thanks a lot for your help and patience!

**Comment by masterix21** [comment]
My pleasure.

**Comment by dseeger** [comment]
Ok, I anyways have a follow-up question: I'm trying to monitor my schedules with oh_dear. All works fine to register with oh dear. But when de scheduled tasks run, sending back a ping to oh dear fails. And it seems to be a multitenancy problem again.

schedule-monitor:list on server:
![2020-10-22_08-51-07](https://user-images.githubusercontent.com/2930193/96835881-777dd900-1444-11eb-9b0e-67eb7e73f7d7.png)

Result in oh dear:
![2020-10-22_08-52-49](https://user-images.githubusercontent.com/2930193/96835907-85335e80-1444-11eb-82ea-490bf2ccb3fa.png)

In the server log I see this:
```
[2020-10-22 01:30:04] production.ERROR: The current tenant could not be determined in a job named `Illuminate\Queue\CallQueuedHandler@call`. No `tenantId` was set in the payload. {"exception":"[object] (Spatie\\Multitenancy\\Exceptions\\CurrentTenantCouldNotBeDeterminedInTenantAwareJob(code: 0): The current tenant could not be determined in a job named `Illuminate\\Queue\\CallQueuedHandler@call`. No `tenantId` was set in the payload. at /home/forge/psicheck.app/vendor/spatie/laravel-multitenancy/src/Exceptions/CurrentTenantCouldNotBeDeterminedInTenantAwareJob.php:12)
[stacktrace]
#0 /home/forge/psicheck.app/vendor/spatie/laravel-multitenancy/src/Actions/MakeQueueTenantAwareAction.php(75): Spatie\\Multitenancy\\Exceptions\\CurrentTenantCouldNotBeDeterminedInTenantAwareJob::noIdSet()
#1 /home/forge/psicheck.app/vendor/spatie/laravel-multitenancy/src/Actions/MakeQueueTenantAwareAction.php(49): Spatie\\Multitenancy\\Actions\\MakeQueueTenantAwareAction->findTenant()
#2 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(391): Spatie\\Multitenancy\\Actions\\MakeQueueTenantAwareAction->Spatie\\Multitenancy\\Actions\\{closure}()
#3 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(236): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#4 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(576): Illuminate\\Events\\Dispatcher->dispatch()
#5 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(393): Illuminate\\Queue\\Worker->raiseBeforeJobEvent()
#6 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Worker->process()
#7 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\\Queue\\Worker->runJob()
#8 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\\Queue\\Worker->daemon()
#9 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#10 /home/forge/psicheck.app/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\\Queue\\Console\\WorkCommand->handle()
#11 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#12 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#13 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#17 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#18 /home/forge/psicheck.app/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#19 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#20 /home/forge/psicheck.app/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#21 /home/forge/psicheck.app/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#22 /home/forge/psicheck.app/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#23 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#24 /home/forge/psicheck.app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#25 /home/forge/psicheck.app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"} 
```

in config/multitenancy.php i have set
`'queues_are_tenant_aware_by_default' => true,`
This might be the problem? But I need this for most of my queues. Do you have any idea how to fix this problem?

**Comment by masterix21** [comment]
I'm sorry, but I can’t help you with OhDear because I have no account on it to try.

I’m sure that @freekmurze will help you.

**Comment by freekmurze** [comment]
@masterix21 if you like I can provide you with a free account as a thank you for your work here.

**Comment by masterix21** [comment]
@freekmurze you are great, man. Yes, thanks: I will do my best to support you and your team.
